// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=.ts"
// @generated from file hello.proto (package hello, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SayHelloRequest, SayHelloResponse } from "./hello_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service hello.HelloService
 */
export const HelloService = {
  typeName: "hello.HelloService",
  methods: {
    /**
     * @generated from rpc hello.HelloService.SayHello
     */
    sayHello: {
      name: "SayHello",
      I: SayHelloRequest,
      O: SayHelloResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

