/**
 * @fileoverview gRPC-Web generated client stub for streaming
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.4
// source: proto/streaming.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.streaming = require('./streaming_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.streaming.FileUploadServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.streaming.FileUploadServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.streaming.DownloadFileRequest,
 *   !proto.streaming.DownloadFileResponse>}
 */
const methodDescriptor_FileUploadService_DownloadFile = new grpc.web.MethodDescriptor(
  '/streaming.FileUploadService/DownloadFile',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.streaming.DownloadFileRequest,
  proto.streaming.DownloadFileResponse,
  /**
   * @param {!proto.streaming.DownloadFileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.streaming.DownloadFileResponse.deserializeBinary
);


/**
 * @param {!proto.streaming.DownloadFileRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.streaming.DownloadFileResponse>}
 *     The XHR Node Readable Stream
 */
proto.streaming.FileUploadServiceClient.prototype.downloadFile =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/streaming.FileUploadService/DownloadFile',
      request,
      metadata || {},
      methodDescriptor_FileUploadService_DownloadFile);
};


/**
 * @param {!proto.streaming.DownloadFileRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.streaming.DownloadFileResponse>}
 *     The XHR Node Readable Stream
 */
proto.streaming.FileUploadServicePromiseClient.prototype.downloadFile =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/streaming.FileUploadService/DownloadFile',
      request,
      metadata || {},
      methodDescriptor_FileUploadService_DownloadFile);
};


module.exports = proto.streaming;

