// @generated by protoc-gen-connect-es v1.4.0
// @generated from file hello.proto (package hello, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SayHelloRequest, SayHelloResponse } from "./hello_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service hello.HelloService
 */
export declare const HelloService: {
  readonly typeName: "hello.HelloService",
  readonly methods: {
    /**
     * @generated from rpc hello.HelloService.SayHello
     */
    readonly sayHello: {
      readonly name: "SayHello",
      readonly I: typeof SayHelloRequest,
      readonly O: typeof SayHelloResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

