// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file proto/streaming.proto (package streaming, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DownloadFileRequest, DownloadFileResponse, UploadFileRequest, UploadFileResponse } from "./streaming_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * FileUploadService is a simple file-sharing service to demonstrate different types of streaming.
 *
 * @generated from service streaming.FileUploadService
 */
export const FileUploadService = {
  typeName: "streaming.FileUploadService",
  methods: {
    /**
     * DownloadFile is a server-streaming RPC method for downloading a file.
     * It takes a filename in the request and streams back the file content in chunks.
     *
     * @generated from rpc streaming.FileUploadService.DownloadFile
     */
    downloadFile: {
      name: "DownloadFile",
      I: DownloadFileRequest,
      O: DownloadFileResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * UploadFile is a client-streaming RPC method for uploading a file.
     * It accepts a stream of bytes, which contains chunks of the file content, and
     * returns a generated file name upon completion.
     *
     * @generated from rpc streaming.FileUploadService.UploadFile
     */
    uploadFile: {
      name: "UploadFile",
      I: UploadFileRequest,
      O: UploadFileResponse,
      kind: MethodKind.ClientStreaming,
    },
  }
} as const;

